### ISSUE TITLE
Problem with -M

### ISSUE THREAD

**Issue by pb-cdunn** [thegenemyers/DALIGNER#31]
The `-M` flags works great ... until it is set too low. Then, it seems to be completely ignored, and memory use rises rapidly. That makes `-M` less useful as a way to limit memory use. We end up relying on `-t`, which is harder to estimate.

Is this a bug, or intended behavior?

**Comment by pb-jchin** [comment]
For large genomes and dataset, `-M` works nice for me in general. Yes, it is still an "art" to get right estimate as any arbitrary genome could be different amount and structure of repeat contain.

**Comment by pb-cdunn** [comment]
Jason, the problem is the non-linear response.

I run 12 jobs on a 48-core machine. With 96GB available, I want just under 8GB per job. That is near-perfect resource use. But if each goes much over 8GB, the machine starts paging and becomes unresponsive.

When `-M` is right, all is well, but if `-M` is slightly low, then suddenly I use more like 32GB per job, and I cannot log into the machine. I'm hoping that it's just a small bug.

**Comment by pb-jchin** [comment]
@pb-cdunn thanks for the insight.  I must admit I seldom set `-M` less then 24G.

**Comment by thegenemyers** [comment]
daligner needs a minimum amount of space depending on block size.  Typically 8Gb or more for blocks of 200-400Mbp.  It is supposed to check and exit if it doesn't have the minimum needed but I think I found a bug that would cause the indicated behavior.  In latest commit.  Please reopen issue if the problem is still there.
