### ISSUE TITLE
"confirmed" vs. "seed" hits

### ISSUE THREAD

**Issue by pb-cdunn** [thegenemyers/DALIGNER#48]
Dr. Myers, I'm having trouble answering this question, so I hope you have time to explain this.

> How can "confirmed hits" be greater than "seed hits"?

**Comment by thegenemyers** [comment]
Seed hits is the number of diagonal bands that meet the seed criterion.
Sometimes there can be two or three disjoint alignments found therein
because of the low-quality drop outs in pacbio reads.  That is there is one
hit between two reads A and B, but because of the low quality regions of
A and B, daligner finds two or three good locally alignment segments between
A and B.

Moreover, confirmed hits is the total number of alignments found, so it 
is generally
twice the number as both A->B and B->A are reported.  Maybe this should 
be fixed
to be half as much again.

    -- Gene
