### ISSUE TITLE
LAshow: Segmentation fault

### ISSUE THREAD

**Issue by pb-cdunn** [thegenemyers/DALIGNER#71]
I've double-checked that this happens with your version too, latest code.
```
LAshow -ac comp raw_reads.comp.las
/bin/sh: line 1: 30550 Segmentation fault      (core dumped)
```
`-c` is fine, and sans flag is fine. Only `-a` crashes. It seems to die somewhere in a `Compute_Trace_Points()`.

* https://downloads.pacbcloud.com/public/falcon/

`gm.tgz` has everything you need. But if you'd rather have original fastas, just let me know, Gene.

**Comment by thegenemyers** [comment]
Actually, LAshow is fine.  The call should be

    'LAshow -ac raw_reads comp raw_reads.comp.las'

You called HPC.daligner with two different databases, 'raw_reads' and 
'comp',
so to list the alignment LAshow needs to be given each database so it can
look up the reads (note that LAcheck in the script does this).  When you 
call
it with only one database, comp, it assumes the A and B reads both come 
from comp
and looks them up there.  Since the A reads come from raw_reads, 
Compute_Trace is
being called with the wrong A read, and so it is comparing some random A 
to the
B-read, so alignment can fail in any number of ways since the trace 
points are no
longer valid.

It was a pain in the ass, but I added checks to Compute trace, so that 
it reports that the
trace is invalid (either because it goes off the end of a read, or 
because it can't find an alignment
with the known difference between two trace points).  So now you get an 
error message about
trace points either being out of bounds or the alignment not making any 
sense, with the tip
that the source DB's may not be specified corrrectly.

    -- Gene
